# vim: ft=tmux.conf

if-shell "test -e /usr/bin/zsh" "set-option -g default-shell /usr/bin/zsh"
if-shell "test -e /bin/zsh" "set-option -g default-shell /bin/zsh"

set-window-option -g mode-keys vi

# set -g mode-mouse off
# set -g default-terminal "screen-256color"

# This seems to be required for neovim to immediately get ESC keypresses
set -sg escape-time 1

# Set window size to maximum for any client connected to *that* window
set -g aggressive-resize on

# Enable mouse
set -g mouse on

