- clean: [ '~', '~/.config', '~/.ssh', '~/.config/upstart', '~/.config/autostart' ]
- link:
    ~/.bashrc: .bashrc
    ~/.gitconfig: .gitconfig
    ~/.ssh/config:
      create: true
      path: .ssh/config
    ~/.tmux.conf: .tmux.conf
    ~/.vimrc: .vimrc
    ~/.inputrc: .inputrc
    ~/.conkyrc: .conkyrc
    ~/.config/autostart/guake.desktop:
      create: true
      path: .config/autostart/guake.desktop
    ~/.config/autostart/conky.desktop:
      create: true
      path: .config/autostart/conky.desktop
    ~/.config/terminator/config:
      create: truconfig
      path: .config/terminator/config
    ~/.config/gtk-3.0/gtk.css:
      create: true
      path: .config/gtk-3.0/gtk.css
    ~/.zshrc: .zshrc
    ~/.zprofile: .zprofile
    ~/.profile: .profile
    ~/.zsh_favlist: .zsh_favlist
    ~/.zsh-custom/themes/agnoster.zsh-theme:
      create: true
      path: .zsh-custom/themes/agnoster.zsh-theme
- shell:
  -
    command: scripts/installOhMyZsh.sh
    stdin: true
    stdout: true
  -
    command: scripts/installVundle.sh
    stdin: true
    stdout: true
  -
    command: scripts/gsettings.sh
    stdin: true
    stdout: true
#  -
#    command: vim +PluginInstall +qall
#    stdin: true
#    stdout: true
