font_size           13.0
font_family         Fira Code
bold_font           auto
italic_font         auto
bold_italic_font    auto
sync_to_monitor yes

background_opacity 0.9

hide_window_decorations yes
inactive_text_alpha 0.5

tab_bar_edge top
tab_bar_style separator

enabled_layouts Tall,Fat

kitty_mod alt
clear_all_shortcuts yes

map kitty_mod+enter new_window
map kitty_mod+k next_window
map kitty_mod+j previous_window

map kitty_mod+l next_tab
map kitty_mod+h previous_tab
map kitty_mod+n new_tab

map kitty_mod+; next_layout
