start on desktop-start
stop on desktop-end

script
    # exec 2>>/home/ishkamiel/.upstart.err
    # exec 1>>/home/ishkamiel/.upstart.log
    # set -x

    echo 'Waiting a few seconds'
    sleep 2;
    if [ -e /usr/bin/guake ]; then
        exec /usr/bin/env DROPDOWNTERMINAL=1 /usr/bin/guake
    elif [ -e /usr/bin/tilda ]; then
        exec /usr/bin/env DROPDOWNTERMINAL=1 /usr/bin/tilda
    fi
end script
