start on desktop-start
stop on desktop-end

instance USER

script
    # Enable logging stuff
    # exec 2>>/home/ishkamiel/.upstart.log
    # exec 1>>/home/ishkamiel/.upstart.log
    # set -x

    # Get some user data
    UID=$(getent passwd "$USER"|cut -d: -f3)
    HOME=$(getent passwd "$USER"|cut -d: -f6)

    echo "UID: $UID"
    echo "HOME: $HOME"

    # Set directory names
    HOME_TMPDIR=$HOME/.tmp
    TMPDIR=/tmp/$UID.$(uptime -s | sed 's/[: -]//g')/$(date +%s)

    # Create tmp root
    mkdir -p $TMPDIR
    
    # Set default permissions
    setfacl -d -m g::- $TMPDIR
    setfacl -d -m o::- $TMPDIR
    
    # Create subdirecotries
    mkdir -p $TMPDIR/vimbackup
    setfacl -d -m g::- $TMPDIR/vimbackup
    setfacl -d -m o::- $TMPDIR/vimbackup

    # Create a link in the home directory
    rm $HOME_TMPDIR 2> /dev/null || true
    ln -s $TMPDIR $HOME_TMPDIR
end script
