start on desktop-start
task

instance USER

script
    # Fish this stuff out
    UID=$(getent passwd "$USER"|cut -d: -f3)
    HOME=$(getent passwd "$USER"|cut -d: -f6)

    # Set directory names
    HOME_TMPDIR=$HOME/.tmp
    TMPDIR=/tmp/$UID.$(uptime -s | sed 's/[: -]//g')/$(date +%s)

    # Create tmp root
    mkdir -p $TMPDIR
    
    # Set default permissions
    setfacl -d -m g::- $TMPDIR
    setfacl -d -m o::- $TMPDIR
    
    # Create subdirecotries
    mkdir -p $TMPDIR/vimbackup

    # Create a link in the home directory
    rm -q $HOME_TMPDIR 2> /dev/null || true
    ln -s $TMPDIR $HOME_TMPDIR
end script
