# vim: ft=sh fdm=marker foldlevel=0
####################################################################################################
#
# This is originally based on agnoster's Theme for ZSH [1], upon which Kenny Root [2] did some
# modifications to adapt it to bash. Although this is a somewhat heavily modified version...
#
# [1] https://gist.github.com/3712874
# [2] https://gist.github.com/kruton/8345450
#
#---------------------------------------------------------------------------------------------------
# SETTINGS

# AGN_PROMPT_GIT=false|FILENAME (default=/usr/lib/git-core/git-sh-prompt)
#----------------------------------------------------
#
# The git shell prompt script uses some environmental variables to customize the proivded
# information. This script takes into acount, but doesn't require the following settings:
#   GIT_PS1_SHOWDIRTYSTATE=true
#   GIT_PS1_SHOWUNTRACKEDFILES=true
#   GIT_PS1_SHOWUPSTREAM="auto"
#   GIT_PS1_SHOWCOLORHINTS=true
# (Please see the the git-shell$GIT_SH_PROMPT file itself for more details)
#---------------------------------------------------------------------------------------------------




####################################################################################################
# __build_prompt
#
# This is the main function that rebuilds the dynamic parts of the prompt. I've elected to use
# inner functions in order to minimize the amount of functions "leaking out". Much of the basic
# parts, like hte __prompt_segment function and call the color functions are from Kenny Root's
# bash converison.
#
# The style is obviously more or less the same as agnoster's theme, but I've change some colors
# to accomodate my color-blindness.
prompt_command() {
    RETVAL=$?
    local use_symbols=false
    local __agn_CURRENT_BG='NONE' # default to no background

    # Check that the characters were displayed and replace with ascii if needed

    local separator=$(echo -ne '\ue0b0') # 

    if [ ${#separator} = 1 ]; then
        use_symbols=true
    else
        separator=' '
    fi

    # Define all the functions that will be needed.
    # Color functions {{{
    text_effect() {
        case "$1" in
            reset)     echo 0;;
            bold)      echo 1;;
            underline) echo 4;;
        esac
    }

    fg_color() {
        case "$1" in
            black)   echo 30;;
            red)     echo 31;;
            green)   echo 32;;
            yellow)  echo 33;;
            blue)    echo 34;;
            magenta) echo 35;;
            cyan)    echo 36;;
            white)   echo 37;;
        esac
    }

    bg_color() {
        case "$1" in
            black)   echo 40;;
            red)     echo 41;;
            green)   echo 42;;
            yellow)  echo 43;;
            blue)    echo 44;;
            magenta) echo 45;;
            cyan)    echo 46;;
            white)   echo 47;;
        esac;
    }

    ansi() {
        local seq
        declare -a thecodes=("${!1}")

        seq=""
        for ((i = 0; i < ${#thecodes[@]}; i++)); do
            if [[ -n $seq ]]; then
                seq="${seq};"
            fi
            seq="${seq}${thecodes[$i]}"
        done
        echo -ne "\[\033[${seq}m\]"
    }

    ansi_single() {
        echo -ne "\[\033[${1}m\]"
    }

    #}}}
    __prompt_segment() { #{{{
        # Begin a segment. Takes two arguments, background and foreground. Both can be omitted,
        # rendering default background/foreground.
        local bg fg

        declare -a codes=($(fg_color $1) $(bg_color $2))

        if [[ -z $1 || ( -z $2 && $2 != default ) ]]; then
            codes=("${codes[@]}" $(text_effect reset))
        fi

        if [[ -n $2 ]]; then
            fg=$(fg_color $2)
            codes=("${codes[@]}" $fg)
        fi

        if [ -n "$1" ]; then
            bg=$(bg_color $1)
            codes=("${codes[@]}" $bg)
        fi

        if [[ $__agn_CURRENT_BG != NONE && $1 != $__agn_CURRENT_BG ]]; then
            declare -a intermediate=($(fg_color $__agn_CURRENT_BG) $(bg_color $1))
            echo -ne " $(ansi intermediate[@])${separator}"
        fi
        echo -ne "$(ansi codes[@])"

        [ -n "${3}" ] && echo -ne "$3"
        __agn_CURRENT_BG=$1
    } #}}}
    __prompt_dir() { # {{{

        __prompt_segment blue black
        pwd | sed "s|^$HOME|~|" | awk -F '/' '
        {
            i=1;
            while (i < NF) {
                if (length($i) > 4) {
                    printf "%s../", substr($i, 1, 2);
                }
            else {
                printf "%s/", $i;
            }
            ++i;
        }
        printf "%s\n", $i; }' | xargs echo -n
    } # }}}
    __prompt_context() { #{{{
        local user=`whoami`
        [[ $user != $DEFAULT_USER || -n $SSH_CLIENT ]] && __prompt_segment cyan black "$user@$(hostname)"
    } #}}}
    __prompt_status() { #{{{
        local symbols=()
        [[ $RETVAL -ne 0 ]] && symbols+="$(ansi_single $(fg_color red))✘"
        [[ $UID -eq 0 ]] && symbols+="$(ansi_single $(fg_color yellow))⚡"
        [[ $(jobs -l | wc -l) -gt 0 ]] && symbols+="$(ansi_single $(fg_color cyan))⚙"
        [[ -n "$symbols" ]] && __prompt_segment black default " $symbols "
    } #}}}
    __prompt_git() { #{{{
        local status=$(gitStatus)

        if [ -n "${status}" ]; then
            if [[ "${status}" =~ [[:space:]] ]]; then
                __prompt_segment magenta black
            else
                __prompt_segment green black
            fi

            echo -ne "${status}"
        fi
    } #}}}

    #DEFAULT_USER=''
    echo -ne "\[\033[0m\]"

    # Build the different components
    __prompt_status
    __prompt_context
    __prompt_dir
    __prompt_git

    # Close of the last segment
    if [ -n "${__agn_CURRENT_BG}" ]; then
        declare -a codes=($(text_effect reset) $(fg_color $__agn_CURRENT_BG))
        echo -ne " $(ansi codes[@])${separator}"
    fi

    # Unset bg variable
    unset __agn_CURRENT_BG
    echo -ne "\[\033[0m\]"
}

####################################################################################################
# Startup

source "${DOTFILES}/.bash/lib/gitStatus"

PROMPT_COMMAND='PS1=$(prompt_command)'
