let onWin = 0
if has("win32") || has("win16")
    let onWin = 1
endif

set nocompatible
filetype off
if onWin
    let path='~/vimfiles/bundle'
    set rtp+=~/vimfiles/bundle/Vundle.vim
else
    set rtp+=~/.vim/bundle/Vundle.vim
endif
call vundle#rc()

Plugin 'gmarik/Vundle.vim'
"Bundle 'tpope/vim-endwise'
"Bundle 'tpope/vim-git'
"Bundle 'tpope/vim-surround'
"
Plugin 'groenewege/vim-less'        " LESS
Plugin 'bling/vim-airline'
Plugin 'DoxygenToolkit.vim'
Plugin 'flazz/vim-colorschemes'
Plugin 'guns/vim-clojure-static'    " Clojure
Plugin 'honza/vim-snippets'
Plugin 'jistr/vim-nerdtree-tabs'
Plugin 'kien/ctrlp.vim'
Plugin 'Lokaltog/vim-easymotion'
Plugin 'maksimr/vim-jsbeautify'     " Javascript
Plugin 'majutsushi/tagbar'
Plugin 'reedes/vim-pencil'
Plugin 'scrooloose/NERDTree'
Plugin 'scrooloose/syntastic'
Plugin 'SirVer/ultisnips'
Plugin 'tcomment'
Plugin 'tpope/vim-fugitive'
Plugin 'Valloric/YouCompleteMe'
Plugin 'vim-perl/vim-perl'          " Perl
Plugin 'Vim-R-plugin'               " R
" Plugin 'c.vim'
" Plugin 'jalcine/cmake.vim'

"-------------------------------------------------------------------------------
" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible
" Use plugins and indent
syntax on
filetype plugin indent on

"-------------------------------------------------------------------------------
" Various settings
"-------------------------------------------------------------------------------
let s:pd_textwidth=100
let s:pd_tab=4

" set autoread              	" read open files again when changed outside Vim
" set autowrite             	" write a modified buffer on each :next , ...
set backspace=indent,eol,start 	" allow backspacing over everything in insert mode
set backup						" keep a backup file
set browsedir=current   		" which directory to use for the file browser
set history=50					" keep 50 lines of command line history
set incsearch             		" use incremental search
set nowrap                		" do not wrap lines
set ruler						" show the cursor position all the time
let &shiftwidth=s:pd_tab  		" number of spaces to use for each step of indent
set showcmd						" display incomplete commands
let &tabstop=s:pd_tab     		" number of spaces that a <Tab> in the file counts for
set expandtab                   " insert spaces instead of tabs
set visualbell 		           	" visual bell instead of beeping
"set textwidth=90 	          	" text width for autoformatt stuff, or something
"set mouse=a
"set ttymouse=xterm2             " fixes urxvt scrolling
let &colorcolumn=s:pd_textwidth
" set autochdir             		" change the current working directory
set exrc                        " find vimrc in working directory
set secure                      " secure loading of non-default vimrc
set pastetoggle=<F9>
set scrolloff=10

set completeopt-=preview        " remove the scratch window preview thingy

set spelllang=en,sv

" Folding
set foldmethod=syntax
set foldlevel=1
set foldcolumn=4
" inoremap <F9> <C-O>za
" nnoremap <A-Space> za
" onoremap <F9> <C-C>za
nnoremap <silent> <Space> @=(foldlevel('.')?'za':"\<Space>")<CR>
vnoremap <Space> zf

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
	syntax on
	set hlsearch
endif

colorscheme 0x7A69_dark
hi FoldColumn ctermfg=DarkCyan ctermbg=8
set guioptions-=m  "remove menu bar
set guioptions-=T  "remove toolbar
set guioptions-=r  "remove right-hand scroll bar
set guioptions-=L  "remove left-hand scroll bar

if onWin
    set lines=40 columns=160
endif

" let s:pd_sidewidth = (&columns - s:pd_textwidth - 2 ) / 2
let s:pd_sidewidth = max([10, min([40, ((&columns - s:pd_textwidth - 10 ) / 2) ])])

set backupdir=~/.vimbackup,.,~/tmp
set directory=~/.vimbackup,.,~/tmp
if onWin
    set backupdir=~/vimbackup
    set directory=~/vimbackup
endif

" Uncomment the following to have Vim jump to the last position when
" reopening a file
if has("autocmd")
   au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" disable arrow keys
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Clojure
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
autocmd BufRead,BufNewFile *.clj setlocal foldlevel=999
autocmd BufRead,BufNewFile *.clj setlocal foldcolumn=0

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" LaTex and textfiles
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
autocmd BufRead,BufNewFile *.tex setlocal spell
autocmd BufRead,BufNewFile *.tex setlocal wrap
autocmd BufRead,BufNewFile *.tex let &textwidth=(s:pd_textwidth-2)
autocmd BufRead,BufNewFile *.tex setlocal formatoptions=t1

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" C++
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set cinoptions+=g0  " don't indent public/private/protected
set cinoptions+=N-s " don't indent namesapces

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" vim-jsbeatuify
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" map <c-r> :call JsBeautify()<cr>
" or
autocmd FileType javascript noremap <buffer>  <c-r> :call JsBeautify()<cr>
" for html
autocmd FileType html noremap <buffer> <c-r> :call HtmlBeautify()<cr>
" for css or scss
autocmd FileType css noremap <buffer> <c-r> :call CSSBeautify()<cr>

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" NERDTree
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" autocmd vimenter * NERDTree
" map <C-n> :NERDTreeToggle<CR>
" autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
" autocmd StdinReadPre * let s:std_in=1
" autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
let g:NERDTreeWinSize=s:pd_sidewidth

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" NERDTree_tabas
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let g:nerdtree_tabs_open_on_gui_startup=1
let g:nerdtree_tabs_open_on_console_startup=1
let g:nerdtree_tabs_no_startup_for_diff=1
let g:nerdtree_tabs_smart_startup_focus=2
let g:nerdtree_tabs_focus_on_files=1

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" airline
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let g:airline#extensions#tabline#enabled = 1

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" YouComepleteMe
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Set YouCompleteMe trigger key
" let g:ycm_key_list_select_completion = ['<Down>']
" let g:ycm_key_list_previous_completion = ['<Up>']
let g:ycm_extra_conf_globlist = ['~/gameProject/*']
let g:ycm_use_ultisnips_completer = 1

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" syntastic stuff
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" set statusline+=%#warningmsg#
" set statusline+=%{SyntasticStatuslineFlag()}
" set statusline+=%*

" let g:syntastic_always_populate_loc_list = 1
" let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_wq = 0

let g:syntastic_check_on_open=1
let g:syntastic_enable_signs=1
let g:syntastic_javascript_checkers = ['jshint']
let g:syntastic_c_check_header = 1
let g:syntastic_mode_map = { 'passive_filetypes': ['html'] } " don't check html

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" TagBar
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
if onWin
    let g:tagbar_ctags_bin = 'C:\Users\ishkamiel\Documents\installs\ctags\ctags.exe'
endif
nmap <F8> :TagbarToggle<CR>
" nmap <F8> :TagbarOpenAutoClose<CR>
let g:tagbar_width=s:pd_sidewidth
autocmd VimEnter * nested :call tagbar#autoopen(1)

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" UltiSnip
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsExpandTrigger="<c-l>"
let g:UtliSnipsEditSplit="normal"
" let g:UltiSnipsListSnippets="<c-Right>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
" let g:UltiSnipsJumpBackwardTrigger="<c-z>"
"

" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"

