server.document-root = "/home/ishkamiel/public_html"

server.port = 3000

mimetype.assign = (
    ".html" => "text/html", 
    ".js" => "text/javascript",
    ".css" => "text/css",
    ".jpg" => "image/jpeg",
    ".png" => "image/png"
)

server.modules = (
    "mod_ssi"
)

ssi.extension = (
    ".html"
)

static-file.exclude-extensions = ( ".fcgi", ".php", ".rb", "~", ".inc" )
index-file.names = ( "index.html" )
