# ZSH
export HISTFILE="$HOME"/.zhistory
setopt SHARE_HISTORY
setopt APPEND_HISTORY
setopt HIST_IGNORE_SPACE
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_REDUCE_BLANKS
# setopt CORRECT
# setopt CORRECT_ALL
HISTSIZE=10000
SAVEHIST=10000
