#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Copyright (C) 2026 Hans Liljestrand <hans@liljestrand.dev>
#
# Font cache refresh and monospace font configuration for GNOME and Kitty.

: <<'__ISH__'
tags = ["isGui"]
run_when = "onchange"
__ISH__

set -euo pipefail

readonly _MONOSPACE_FONTS=(
  "FiraCode Nerd Font Mono,FiraCode Nerd Font Mono Ret"
  "FiraCode Nerd Font Mono"
  "Ubuntu Mono"
  "Courier"
)

__find_first_available_font() {
  local _available
  _available=$(fc-list :spacing=mono family 2>/dev/null \
    | sed 's/,.*//;s/:.*//' \
    | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' \
    | sort -u)

  for _pref in "$@"; do
    if echo "${_available}" | grep -qi "^${_pref}$"; then
      echo "${_pref}"
      return
    fi
  done

  local _first
  _first=$(echo "${_available}" | head -1)
  [[ -n "${_first}" ]] && echo "${_first}"
}

__configure_gnome_font() {
  if ! command -v dconf >/dev/null 2>&1; then
    return 0
  fi
  local _monospace_font
  _monospace_font=$(__find_first_available_font "${_MONOSPACE_FONTS[@]}")
  if [[ -n "${_monospace_font}" ]]; then
    dconf write /org/gnome/desktop/interface/monospace-font-name "'${_monospace_font}'"
    ish_info "Set GNOME monospace font: ${_monospace_font}"
  fi
}

__configure_kitty_font() {
  local _kitty_conf_dir="${HOME}/.config/kitty"
  [[ -d "${_kitty_conf_dir}" ]] || return 0

  local _monospace_font
  _monospace_font=$(__find_first_available_font "${_MONOSPACE_FONTS[@]}")
  [[ -n "${_monospace_font}" ]] || return 0

  printf '# Generated by 92_fonts.sh — do not edit by hand\nfont_family %s\n' \
    "${_monospace_font}" > "${_kitty_conf_dir}/font.conf"
  ish_info "Set kitty font: ${_monospace_font}"
}

fc-cache -f "${HOME}/.local/share/fonts"
ish_info "Font cache refreshed"

__configure_gnome_font
__configure_kitty_font
