# vim: ft=tmux.conf

if-shell "test -e /usr/bin/zsh" "set-option -g default-shell /usr/bin/zsh"
if-shell "test -e /bin/zsh" "set-option -g default-shell /bin/zsh"

if-shell "test -e ~/.local.tmux.conf" "source-file ~/.local.tmux.conf"

set -g default-terminal "screen-256color"

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# Move panes with hjkl, without wrapping
bind h if-shell "[ $(tmux display-message -p '#{pane_at_left}') != 1 ]" "select-pane -L"
bind j if-shell "[ $(tmux display-message -p '#{pane_at_bottom}') != 1 ]" "select-pane -D"
bind k if-shell "[ $(tmux display-message -p '#{pane_at_top}') != 1 ]" "select-pane -U"
bind l if-shell "[ $(tmux display-message -p '#{pane_at_right}') != 1 ]" "select-pane -R"

# Move panes with hjkl, without wrapping, and in any mode
# bind -n M-h if-shell "[[ $(tmux display-message -p '#{pane_at_left}') == 1 ]]" "select-pane -L"
# bind -n M-j if-shell "[[ $(tmux display-message -p '#{pane_at_bottom}') == 1 ]]" "select-pane -D"
# bind -n M-k if-shell "[[ $(tmux display-message -p '#{pane_at_top}') == 1 ]]" "select-pane -U"
# bind -n M-l if-shell "[[ $(tmux display-message -p '#{pane_at_right}') == 1 ]]" "select-pane -R"

bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# For nested tmux
bind-key -n c-g send-prefix
bind-key -n c-t send-keys c-g

# This seems to be required for neovim to immediately get ESC keypresses
set -sg escape-time 1

# Set window size to maximum for any client connected to *that* window
set -g aggressive-resize on

# Enable mouse
set -g mouse on
