# vim: ft=tmux.conf

if-shell "test -e /usr/bin/zsh" "set-option -g default-shell /usr/bin/zsh"
if-shell "test -e /bin/zsh" "set-option -g default-shell /bin/zsh"

if-shell "test -e ~/.local.tmux.conf" "source-file ~/.local.tmux.conf"

set -g default-terminal "screen-256color"

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# set -g mode-mouse off
# set -g default-terminal "screen-256color"

# This seems to be required for neovim to immediately get ESC keypresses
set -sg escape-time 1

# Set window size to maximum for any client connected to *that* window
set -g aggressive-resize on

# Enable mouse
set -g mouse on
